// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVwCog6rySocxtGOhyBqEFFx5xo00v1Fg',
    appId: '1:40549094141:web:4d227c1e4c73d424226494',
    messagingSenderId: '40549094141',
    projectId: 'suav-nyiaj-ya',
    authDomain: 'suav-nyiaj-ya.firebaseapp.com',
    storageBucket: 'suav-nyiaj-ya.firebasestorage.app',
    measurementId: 'G-RWGRXW48H9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcwk1e_IaI0uWyj5yNOD73uf9NlLN2jNU',
    appId: '1:40549094141:android:7c73a04bcf1f479e226494',
    messagingSenderId: '40549094141',
    projectId: 'suav-nyiaj-ya',
    storageBucket: 'suav-nyiaj-ya.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW2Hz3smeyIeXtaY5k8xx5Qa5X8eeN9N4',
    appId: '1:40549094141:ios:9f85370de36f7949226494',
    messagingSenderId: '40549094141',
    projectId: 'suav-nyiaj-ya',
    storageBucket: 'suav-nyiaj-ya.firebasestorage.app',
    androidClientId: '40549094141-0cdei0mbsnltr1allk2ehl7l5jqj2sat.apps.googleusercontent.com',
    iosClientId: '40549094141-e2lih9rsrijfjctdeoro1a625njgo0du.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodpandaAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW2Hz3smeyIeXtaY5k8xx5Qa5X8eeN9N4',
    appId: '1:40549094141:ios:9f85370de36f7949226494',
    messagingSenderId: '40549094141',
    projectId: 'suav-nyiaj-ya',
    storageBucket: 'suav-nyiaj-ya.firebasestorage.app',
    androidClientId: '40549094141-0cdei0mbsnltr1allk2ehl7l5jqj2sat.apps.googleusercontent.com',
    iosClientId: '40549094141-e2lih9rsrijfjctdeoro1a625njgo0du.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodpandaAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVwCog6rySocxtGOhyBqEFFx5xo00v1Fg',
    appId: '1:40549094141:web:01612880a7df5ada226494',
    messagingSenderId: '40549094141',
    projectId: 'suav-nyiaj-ya',
    authDomain: 'suav-nyiaj-ya.firebaseapp.com',
    storageBucket: 'suav-nyiaj-ya.firebasestorage.app',
    measurementId: 'G-7VXX3TYJ1W',
  );
}
